# Code generated by protoc-gen-twirp_ruby 1.4.1, DO NOT EDIT.
require 'twirp'
require_relative 'people_pb.rb'

class PeopleService < Twirp::Service
  service 'People'
  rpc :getName, GetNameRequest, GetNameResponse, :ruby_method => :get_name
end

class PeopleClient < Twirp::Client
  client_for PeopleService
end
